name: 'Melon Ticket Notifier'
description: 'GitHub action that notifies ticket availability'
author: 'MooYeol Prescott Lee'
inputs:
  product-id: 208789
    description: 'Product ID of Target Ticket'
    required: true
  schedule-id: 100001
    description: 'Schedule ID of Target Ticket'
    required: true
  seat-id: 
    description: 'Seat Id of Target Ticket'
    required: true
  slack-incoming-webhook-url: ${{ https://hooks.slack.com/services/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 }}
    description: 'URL of Slack Incoming Webhook'
    required: true
  message: 
    description: 'Message'
    required: false
    default: '티켓사세요'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'music'
  color: 'green'
